Task 9の提出。
H-Shira/kintone_dojo pull request #11
Opened 2022-07-11 08:02 UTC by H-Shira

@tokunagago 
お疲れ様です。
改めてtask9を提出させていただきます。
課題はフォルダ「other tasks」の「task9.js」になります。ログは「task9_log.md」になります。
よろしくお願いいたします。

2022-07-11 08:33 UTC, tokunagago requested changes
@H-Shira レビューしました！
少しずつ難しくなってきましたね。
レビューで不明点あればいつでも遠慮なくどうぞ！

2022-07-11 08:33 UTC, tokunagago commented on other tasks/task9.js
> +  let uniqueName;
`uniqueName` は6行目からの `kintone.events.on` 内でのみ使用するので、`kintone.events.on` の内側に書きましょう！

2022-07-11 08:33 UTC, tokunagago commented on other tasks/task9.js
> +    console.log(uniqueName);
提出時は `console.log` を削除しておきましょう！

2022-07-11 08:33 UTC, tokunagago commented on other tasks/task9.js
> +      'app': 31,
```suggestion
      app: kintone.app.getId(),
```

同一アプリなので、`getId()` でIDを指定しましょう！

2022-07-11 08:33 UTC, tokunagago commented on other tasks/task9.js
> +      };
if文の閉じカッコにセミコロン `;` は不要です！

2022-07-11 08:33 UTC, tokunagago commented on other tasks/task9.js
> +      'query': '重複禁止項目 = "' + uniqueName + '"'
```suggestion
      'query': `重複禁止項目 = "${uniqueName}" `
```

クエリーの値はシングルクォートとダブルクォートが混じってしまい読みにくくなっているので、テンプレートリテラルを使って書き換えてみましょう！

また、現状のクエリーだと、
編集画面で何も変更せずに保存したときに「レコードが重複しています。」のアラートが出てしまいます。
そのため、レコード編集時は現在編集中のレコードを含めないようなクエリーにする必要があります！
つまり、レコード新規追加時と編集時でクエリーをわける条件分岐が必要です！

2022-07-14 06:19 UTC, H-Shira commented
@tokunagago 
お疲れ様です！
レビューいただいた内容の修正が完了いたしました。
ご確認お願いいいたします🙇‍♀️

2022-07-14 08:16 UTC, tokunagago commented
@H-Shira 
修正ありがとうございます！
実装方針を変えるとシンプルに書けるので下記を参考に修正してみてください！
なかなか難しいところですので、不明点あればいつでもどうぞ！

今回、新規追加時と編集時のイベントを２つ用意してイベントハンドラも２つにわけているのですが、イベントハンドラは1つで書くことができます！
```
kintone.events.on(['app.record.create.submit', 'app.record.edit.submit'], (event) => {
```

そして、クエリのみをイベントに応じて変更すればOKです！
イベントは `event.type` で取得できます！
クエリの内容ですが、編集時は編集中のレコードを検索対象から除きたいので、
クエリーに `$id != ${event.record.$id.value}`を追加することで除くことができます！
参考：https://developer.cybozu.io/hc/ja/articles/202331474#q1:~:text=%E3%81%95%E3%82%8C%E3%81%BE%E3%81%99%E3%80%82-,!%3D,-%E6%96%87%E5%AD%97%E5%88%97_0

```
if (event.type === 'app.record.create.submit') {
  query = `重複禁止項目 = "${value}" `;
} else {
  query = `重複禁止項目 = "${value}" and  $id != ${event.record.$id.value} `;
}
```

もしくは `event`オブジェクトに、
・編集時はレコードIDがあり
・新規作成時はレコードIDがない（まだレコードが登録されていないため）
ので、レコードIDの有無でも編集時なのか新規作成時なのかを判別できます！

2022-07-14 09:55 UTC, H-Shira commented
@tokunagago 
お疲れ様です！
> イベントは event.type で取得できます！
そうだったんですね…！二種類書くしかないのかと思っていました…！学びになりました、ありがとうございます🙇‍♀️🙇‍♀️

修正が完了したため、再度レビューいただきたいです。
お忙しい中恐縮ですが、お願い致します🙇‍♀️

2022-07-14 10:33 UTC, tokunagago requested changes
@H-Shira なかなか難しいところですがもう少しです！
確認をお願いします！

2022-07-14 10:33 UTC, tokunagago commented on other tasks/task9.js
> +    };
レコード編集時は開いているレコードを検索対象に含めたくないので、`query` をレコード新規作成時と編集時でわけたほうがよいですね。
検索対象に含めないためには前回のレビューにある通り `$id != ${event.record.$id.value}` をつけるとよいです！

そのように書くことで、レコード新規作成時と編集時のREST APIの実行を共通化できます！
その結果、コードの量が半分くらいになるはずです！

イメージ
```
let query;
if (新規作成時) {
  query = `重複禁止項目 = "${uniqueName}" `;
} else if (編集時) {
  query = `重複禁止項目 = "${uniqueName}"  and  $id != ${event.record.$id.value} `;
}

const paramsCreate = {
  'fields': '重複禁止項目',
  'app': kintone.app.getId(),
  'query': query  // queryの値は if文の条件式に応じて決まる
};

// 残りのREST APIの実行は白坂さんが書いてくれている通り（のはず）
return kintone.api(kintone.api.url('/k/v1/records.json', true), 'GET', paramsCreate).then((resp) => {
  if (resp.records.length !== 0) {
    const response = confirm('レコードが重複しています。このまま保存しますか？');
      if (response === false) {
        return false;
      }
    }
});
```

2022-07-19 01:24 UTC, H-Shira commented
@tokunagago 
お疲れ様です！
queryでかなり抽出条件を絞ることができるんですね…！個人的に書き方がかなり難しいところなので（バッククォートの位置が複雑です…）意識して覚えていきたいと思います。
レビュー後の修正が完了したので、お忙しい中恐縮ですがご確認をお願い致します🙇‍♀️

2022-07-20 08:18 UTC, merged

2022-07-20 08:21 UTC, tokunagago commented
@H-Shira OKです、これで課題すべて完了ですね！
大変だったことが多かったと思いますがやりきりましたね！
プログラミング能力が向上したはずです！
お疲れ様でした🎉