Task 6の提出。
H-Shira/kintone_dojo pull request #6
Opened 2022-07-04 09:13 UTC by H-Shira

@tokunagago 
お疲れ様です。
task6が完了したため、レビューをお願い致します🙇‍♀️
課題は「task6.js」になります。

2022-07-04 23:48 UTC, tokunagago requested changes
@H-Shira ほぼOKです！
テーブルへの `push` もシンプルに書けていてGoodです！
細かい箇所ですが修正をお願いします！

2022-07-04 23:48 UTC, tokunagago commented on day6/task6.js
> +        let addRow = event.record.Table;
`addRow` だと動詞なので関数のように見えてしまうので `table` とかのほうがよいですね！

2022-07-04 23:48 UTC, tokunagago commented on day6/task6.js
> +        console.log(addRow);
提出時は基本的に `console.log` を削除しておきましょう！
4行目も同様です！
（エラー処理や課題としてコンソールに出力する場合は除く）

2022-07-04 23:48 UTC, tokunagago commented on day6/task6.js
> +            '公明正大',
`'公明正大',` のカンマは最後の要素のため削除しておきましょう！

2022-07-04 23:48 UTC, tokunagago commented on day6/task6.js
> +        action5.forEach((title, index) => {
`index` はforEach内で使っていないので削除してください！
第2引数（`index`）は省略可能です！
参考：https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#parameters

2022-07-05 00:29 UTC, H-Shira commented
@tokunagago 
お疲れ様です！ご丁寧なレビューありがとうございます🙇‍♀️
いただいた内容からコード修正を行いました。
お忙しい中恐縮ですが、ご確認お願い致します🙇‍♀️

2022-07-05 00:34 UTC, tokunagago approved these changes

2022-07-05 00:34 UTC, tokunagago commented
@H-Shira OKです！早速の修正ありがとうございます！
お疲れ様でした！

2022-07-05 00:34 UTC, merged