task7のレビュー依頼。
H-Shira/kintone_dojo pull request #7
Opened 2022-07-05 08:06 UTC by H-Shira

@tokunagago 
お疲れ様です。task7が完了したので、レビューをお願い致します。
課題は「task7.js」、課題のログは「task7_log.md」になります。
お忙しい中恐縮ですが、よろしくお願い致します🙇‍♀️

2022-07-05 08:48 UTC, tokunagago requested changes
`app.record.create.change.重複禁止項目_自動計算` としたのはとても賢い書き方ですね！
レビューしたので確認をお願いします！

2022-07-05 08:48 UTC, tokunagago commented on day7/task7.js
> +    });
4行目から14行目について
新規登録時と編集時の動作は同じなので、イベントを配列として書くとシンプルに書くことができます！

```
    kintone.events.on(['app.record.edit.show', 'app.record.edit.show'], (event) => {
        event.record.重複禁止項目_文字列.disabled = true;
        return event;
    });
```

参考：https://developer.cybozu.io/hc/ja/articles/201941954-イベント処理の記述方法
参考のURLの「イベントハンドラーを登録する」>「プロパティ」のタイプで配列も可能であることが確認できます。

16行目から32行目も同様に修正してみてください！

2022-07-05 09:22 UTC, H-Shira commented
@tokunagago 
お疲れ様です。
配列にするとイベントをまとめることができるんですね…！学びになりました、ありがとうございます🙇‍♀️
再度提出させていただいたので、お手隙の際にご確認お願い致します。

2022-07-06 07:58 UTC, tokunagago approved these changes

2022-07-06 07:58 UTC, merged

2022-07-06 07:59 UTC, tokunagago commented
@H-Shira レビュー遅れてすみません！
OKです！お疲れ様でした！