Task 8の提出
H-Shira/kintone_dojo pull request #9
Opened 2022-07-07 07:32 UTC by H-Shira

@tokunagago 
お疲れ様です。
task8が完了したため、レビューをお願い致します。
課題は「other tasks」ファイルの「task8.js」になります。
お忙しい中恐縮ですが、よろしくお願い致します。

2022-07-08 06:32 UTC, tokunagago requested changes
ほぼOKです！
オブジェクトから配列を作っている23行目から26行目はとてもシンプルでよいですね！
軽微な修正ですが確認をお願いします！

2022-07-08 06:32 UTC, tokunagago commented on other tasks/task8.js
> +        console.log(event);
提出時は `console.log` を削除しておきましょう！

2022-07-08 06:32 UTC, tokunagago commented on other tasks/task8.js
> +        event.record.Table.value = [];
`event.record.Table.value = [];` が必要になるのは12行目のREST APIが成功した場合になるので、12行目より下のREST APIの処理の中に書きましょう！
（12行目のREST APIで失敗した場合、 `event.record.Table.value = [];` を不要に呼び出していることになる）

2022-07-08 06:32 UTC, tokunagago commented on other tasks/task8.js
> +        return kintone.api(kintone.api.url('/k/v1/app/form/fields.json', true), 'GET', params,) .then ((resp) => {
不要なカンマと半角スペースを削除しておきましょう！
（params の後ろと then の前後）
```
return kintone.api(kintone.api.url('/k/v1/app/form/fields.json', true), 'GET', params).then((resp) => {
```

2022-07-08 06:32 UTC, tokunagago commented on other tasks/task8.js
> +            app: 38,
現在開いているアプリIDを設定することができます！
参考：https://developer.cybozu.io/hc/ja/articles/202166300-アプリID取得

```suggestion
            app: kintone.app.getId(),
```

2022-07-11 08:16 UTC, H-Shira commented
@tokunagago 
お疲れ様です！
レビュー確認後、修正内容で再提出させていただきました。
お忙しい中恐縮ですが、レビューをお願いいたします。

2022-07-11 08:52 UTC, tokunagago approved these changes
@H-Shira OKです！
不要なコメントの削除だけお願いします！
削除したら白坂さんがマージしてOKです！

2022-07-11 08:52 UTC, tokunagago commented on other tasks/task8.js
> +      //console.log(action5Array);
不要なコメントは削除しておきましょう！

2022-07-11 09:09 UTC, H-Shira commented
@tokunagago 
承知いたしました！ご確認ありがとうございました🙇‍♀️

2022-07-11 09:10 UTC, merged